#!/bin/bash

sha=$1
dir=$2

rm -rf $dir/R.$sha
> $dir/F.$sha

gen() {
	echo 12345670123456 > /tmp/cap
	((s=$2-$1+1+2))
	truncate /tmp/cap -s $s
	./xcache-combine-one $sha $dir /tmp/cap 2 10 $1 $2
	hexdump -C $dir/F.$sha
}

gen 3 4
gen 0 2
gen 3 6
gen 5 9
gen 2 3
gen 2 4
gen 1 5

