#!/usr/bin/perl

sub T {
	$s = @_[0];
	$r = `./xcache-should-overwrite /tmp/R $s`;
	if ($r =~ /^ok/) { `printf "$s" > /tmp/R`; }
	print "in=$s result=$r";
}

`rm -rf /tmp/R`;
T "1-2/10";
T "1-2/10";
T "1-4/10";
T "1-3/10";
T "0-9/10";
T "0-9/10";

