#!/bin/sh
### BEGIN INIT INFO
# Provides:          xcache
# Required-Start:    $syslog $network
# Required-Stop:     $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the xcache system.
### END INIT INFO

. /lib/lsb/init-functions

do_start()
{
	log_daemon_msg "Starting Xcache Pcap daemon" xcache-pcap
	if ! start-stop-daemon --start --oknodo -b -m --quiet \
		--pidfile /var/run/xcache-pcap.pid --exec /usr/bin/xcache-pcap 
	then
		log_end_msg 1
	else
		log_end_msg 0
	fi

	log_daemon_msg "Starting Xcache Processing daemon" xcache-proc
	if ! start-stop-daemon --start --oknodo -b -m --quiet \
		--pidfile /var/run/xcache-proc.pid --exec /usr/bin/xcache-proc
	then
		log_end_msg 1
	else
		log_end_msg 0
	fi
}

do_stop()
{
	log_daemon_msg "Stopping Xcache Pcap daemon" xcache-pcap
	if start-stop-daemon --stop --oknodo -s 9 --quiet \
		--pidfile /var/run/xcache-pcap.pid --exec /usr/bin/xcache-pcap
	then
			rm -f /var/run/xcache-pcap.pid 
			log_end_msg 0
	else
			log_end_msg 1
	fi

	log_daemon_msg "Stopping Xcache Processing daemon" xcache-proc
	if start-stop-daemon --stop --oknodo -s 9 --quiet \
		--pidfile /var/run/xcache-proc.pid 
	then
			rm -f /var/run/xcache-proc.pid 
			log_end_msg 0
	else
			log_end_msg 1
	fi
}

case "$1" in
    start)
				do_start
        ;;
    stop)
				do_stop
				;;
		restart)
				do_stop
				do_start
				;;
    status)
        status_of_proc -p /var/run/xcache-pcap.pid /usr/lib/xcache-pcap xcache-pcap && exit 0 || exit $?
        ;;
    *)
        echo "Usage: /etc/init.d/xcache {start|stop|restart|status}" >&2
        exit 1
        ;;
esac

exit 0

