#!/usr/bin/perl

`echo >> /l/L`;
`echo ====== starts ======= >> /l/L`;
`echo >> /l/L`;
while (1) {
	open F, "find /c/ -name '[FGZ].*' |";
	while (<F>) {
		`do=1 xcache-reap-one $_`;
		`rm -rf $_`;
	}
	close F;
	sleep 1;
}

