#!/usr/bin/python

import os, glob, sys, marshal

sha = sys.argv[1]
rootdir = sys.argv[2]

clen = int(open('%s/I.%s' % (rootdir, sha)).read())

arr = []
for f in glob.glob('%s/CF.%s.*' % (rootdir, sha)):
	basename = os.path.basename(f)
	cf, sha, s, e = basename.split('.')
	s = int(s)
	e = int(e)
	hl = int(open('%s/I.%s.%d.%d' % (rootdir, sha, s, e)).read())
	print basename, s, e, hl
	arr.append((s, e, f, hl))

res = []
rm = []
for i in arr:
	s, e, f, hl = i
	r = False
	for j in arr:
		s2, e2, f2, hl2 = j
		if s2 <= s and e <= e2 and i != j:
			r = True
	if r == False:
		res.append((s, e, f, hl))
	else:
		rm += [f, f.replace('CF', 'CH'), f.replace('CF', 'I')]

res = sorted(res)

#open('%s/RS.%s' % (rootdir, sha), 'w+').write(''.join(
#	[' '.join(i)+'\n' for i in res]
#))
marshal.dump((clen, res), open('%s/RSM.%s' % (rootdir, sha), 'wb+'))
open('%s/RM.%s' % (rootdir, sha), 'w+').write(''.join(
	[i+'\n' for i in rm]
))
#print sorted(res)
#print rm


