#!/usr/bin/perl

sub proc {
	return if ! -f $f;
	($s, $e, $clen) = `cat $f` =~ /(\d+)-(\d+)\/(\d+)/;
	($s2, $e2) = $in =~ /(\d+)-(\d+)?/;
	$e2 = $clen-1 if !$e2;
	if ($s <= $s2 && $e2 <= $e && $e2 >= $s2) {
		print "ok-rs=",$s2-$s,"&rl=",$e2-$s2+1;
	}
}
($f, $in) = @ARGV;
if ($f) { proc; }
else { while (<STDIN>) { chomp(($f, $in) = split / /, $_); proc; }}


