#!/usr/bin/perl

sub fuck { print "failed @_[0]\n"; exit; }
sub proc {
	fuck "youku start= unsupported" if ($url =~ /youku/ && $url =~ /start=/);
	print "ok\n";
}
($url, $ext) = @ARGV;
if ($url) { proc; exit }
else { while (<STDIN>) { chomp($url = $_); proc } }

