#!/usr/bin/perl

`echo >> /l/L`;
`echo ====== starts ======= >> /l/L`;
`echo >> /l/L`;
open F, "dir=/c xcache-inotify |";
while (<F>) {
	`do=1 xcache-reap-one /c/$_`;
	`rm -rf $_`;
}
close F;
sleep 1;

